### ISSUE TITLE
Plugin breaks the upload tab in the media library modal

### ISSUE THREAD

**Issue by adamk22** [webbistro/enhanced-media-library#2]
**Versions**
Wordpress Version: 5.3
Plugin Version: 2.7.2

**Steps to reproduce this issue:**
1. Create a new post
2. Set a featured Image
3. Media modal pops up, select the Upload Files tab
4. Upload modal turns blank, JS error shows up in the console: `TypeError: this.obj._listeners is undefine`.

<img width="1462" alt="Screenshot 2020-03-05 at 12 05 38" src="https://user-images.githubusercontent.com/1798070/75975997-d86a9800-5ed9-11ea-83d1-25d4aae0adf0.png">

Related: https://github.com/WordPress/gutenberg/issues/19382

**Comment by ogrosko** [comment]
Can confirm same problem with WP 5.3.2 and Enhanced Media Library plugin. After deactivating plugin all works fine.

**Comment by vmank** [comment]
Any updates on this? Is there any work around besides removing the plugin?

**Comment by Harm10** [comment]
I have this problem too! Will this be fixed soon?

**Comment by brycejackson** [comment]
Check here for solutions and/or working 5.3 version: 
https://github.com/woody-wordpress/enhanced-media-library
https://gist.github.com/KZeni/da1a76b2d93d01190cf9de7067b8a982
